# ---------------------------------------------------------------------------------------
# Postgres
# YTI Fuseki
# YTI Groupmanagement - Groupmanagement API + UI bundle
# YTI ActiveMQ - Active MQ
# YTI ElasticSearch - Elastic Search
# YTI Codelist - Intake Service
# YTI Codelist - Public API Service
# YTI Codelist - UI
# YTI Terminology - Termed API
# YTI Terminology - API
# YTI Terminology - UI
# YTI Datamodel - API
# YTI Datamodel - UI
# YTI Comments - API
# YTI Comments - UI
# ---------------------------------------------------------------------------------------

version: '3.9'

services:

  # KIBANA
  # Just uncomment if you need to analyze indexes
  #yti-kibana:
  #  image: docker.elastic.co/kibana/kibana:6.5.4
  #  container_name: yti-kibana
  #  restart: always
  #  ports:
  #   - "5601:5601"
  #  environment:
  #    ELASTICSEARCH_URL: http://yti-elasticsearch:9200
  #  networks:
  #   - yti-network

  # ELASTIC SEARCH
  yti-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.22
    container_name: yti-elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - network.host=0.0.0.0
      - network.bind_host=0.0.0.0
      - network.publish_host=127.0.0.1
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - yti-network

  # POSTGRES
  yti-postgres:
    image: yti-postgres:latest
    container_name: yti-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /data/logs/yti-postgres:/data/logs/yti-postgres:Z
      - /data/postgres/data:/var/lib/postgresql/data
    command: postgres -c logging_collector=on -c log_directory=/data/logs/yti-postgres -c max_connections=250
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - yti-network

  # ACTIVEMQ
  yti-activemq:
    image: yti-activemq:latest
    container_name: yti-activemq
    restart: always
    ports:
      - "9900:8161"
      - "9901:61616"
    environment:
      - "ARTEMIS_USERNAME=yti"
      - "ARTEMIS_PASSWORD=test"
      - "ARTEMIS_MIN_MEMORY=512M"
      - "ARTEMIS_MAX_MEMORY=512M"
    volumes:
      - /data/logs/yti-activemq:/var/lib/artemis/log:z
    networks:
      - yti-network

  # GROUPMANAGEMENT
  yti-groupmanagement:
    image: yti-groupmanagement:latest
    container_name: yti-groupmanagement
    restart: always
    ports:
      - "9302:9302"
      - "9300:9300"
    volumes:
      - ./config:/config
    environment:
      - ANGULAR_PRODUCTION
      - ANGULAR_KEYCLOAK_URL
      - ANGULAR_KEYCLOAK_REALM
      - ANGULAR_KEYCLOAK_CLIENT_ID
      - ANGULAR_BASE_HREF=${GROUPMANAGEMENT_BASE_HREF}
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_MAIL_HOST=${MAIL_HOST}
      - ENVIRONMENT_MAIL_PORT=${MAIL_PORT}
      - ENVIRONMENT_MAIL_USERNAME=${MAIL_USERNAME}
      - ENVIRONMENT_MAIL_PASSWORD=${MAIL_PASSWORD}
      - ENVIRONMENT_MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - ENVIRONMENT_MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - ENVIRONMENT_MAIL_SMTP_STARTTLS_REQUIRED=${MAIL_SMTP_STARTTLS_REQUIRED}
      - ENVIRONMENT_ADMIN_EMAIL=${ADMIN_EMAIL}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_PUBLIC_URL}
      - ENVIRONMENT_COMMENTS_PUBLICURL=${COMMENTS_PUBLIC_URL}
      - ENVIRONMENT_DATAMODEL_PUBLICURL=${DATAMODEL_PUBLIC_URL}
      - ENVIRONMENT_TERMINOLOGY_PUBLICURL=${TERMINOLOGY_PUBLIC_URL}
      - ENVIRONMENT_GROUPMANAGEMENT_PUBLICURL=${GROUPMANAGEMENT_PUBLIC_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-groupmanagement.yml"
    depends_on:
      - yti-postgres
      - yti-keycloak
    links:
      - yti-postgres
      - yti-keycloak
    networks:
      - yti-network

  # CODELIST
  yti-codelist-ui:
    image: yti-codelist-ui:latest
    container_name: yti-codelist-ui
    privileged: true
    environment:
      - CODELIST_API_URL
      - CODELIST_INTAKE_URL
      - TERMINOLOGY_API_URL
      - MESSAGING_API_URL
      - ANGULAR_PRODUCTION
      - ANGULAR_KEYCLOAK_URL
      - ANGULAR_KEYCLOAK_REALM
      - ANGULAR_KEYCLOAK_CLIENT_ID
      - ANGULAR_BASE_HREF=${CODELIST_BASE_HREF}
    ports:
      - "9600:80"
    depends_on:
      - yti-codelist-content-intake-service
      - yti-codelist-public-api-service
      - yti-messaging-api
      - yti-terminology-api
    links:
      - yti-codelist-content-intake-service
      - yti-codelist-public-api-service
      - yti-messaging-api
      - yti-terminology-api
    networks:
      - yti-network

  yti-codelist-content-intake-service:
    image: yti-codelist-content-intake-service:latest
    container_name: yti-codelist-content-intake-service
    restart: always
    ports:
      - "9602:9602"
      - "9603:9603"
      - "19602:19602"
    volumes:
      - ./config:/config
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_PUBLIC_URL}
      - ENVIRONMENT_COMMENTS_PUBLICURL=${COMMENTS_PUBLIC_URL}
      - ENVIRONMENT_TERMINOLOGY_PUBLICURL=${TERMINOLOGY_PUBLIC_URL}
      - ENVIRONMENT_DATAMODEL_PUBLICURL=${DATAMODEL_PUBLIC_URL}
      - ENVIRONMENT_GROUPMANAGEMENT_PUBLICURL=${GROUPMANAGEMENT_PUBLIC_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-codelist-content-intake-service.yml"
    command: -j -Xmx512M
    depends_on:
      - yti-groupmanagement
      - yti-elasticsearch
      - yti-postgres
      - yti-keycloak
    links:
      - yti-groupmanagement
      - yti-elasticsearch
      - yti-postgres
      - yti-keycloak
    networks:
      - yti-network

  yti-codelist-public-api-service:
    image: yti-codelist-public-api-service:latest
    container_name: yti-codelist-public-api-service
    restart: always
    ports:
      - "9601:9601"
      - "19601:19601"
    volumes:
      - ./config:/config
      - /data/logs/yti-codelist-api:/data/logs/yti-codelist-api:Z
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_PUBLIC_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-codelist-public-api-service.yml"
    command: -j -Xmx512M
    depends_on:
      - yti-elasticsearch
      - yti-keycloak
    links:
      - yti-elasticsearch
      - yti-keycloak
    networks:
      - yti-network

  # TERMINOLOGY
  yti-terminology-termed-api:
    image: "yti-terminology-termed-api:latest"
    container_name: "yti-terminology-termed-api"
    restart: always
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-terminology-termed-api.yml"
    ports:
      - "9102:9102"
    volumes:
      - ./config:/config:Z
      - /data/logs/yti-terminology-termed-api:/data/logs/yti-terminology-termed-api:Z
    depends_on:
      - yti-postgres
    links:
      - yti-postgres
    networks:
      - yti-network

  yti-terminology-api:
    image: "yti-terminology-api:latest"
    container_name: "yti-terminology-api"
    restart: always
    ports:
      - "9101:9101"
      - "9103:9103"
    volumes:
      - ./config:/config:Z
      - /data/logs/yti-terminology-api:/data/logs/yti-terminology-api:Z
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_PUBLIC_URL}
      - ENVIRONMENT_COMMENTS_PUBLICURL=${COMMENTS_PUBLIC_URL}
      - ENVIRONMENT_DATAMODEL_PUBLICURL=${DATAMODEL_PUBLIC_URL}
      - ENVIRONMENT_GROUPMANAGEMENT_PUBLICURL=${GROUPMANAGEMENT_PUBLIC_URL}
      - ENVIRONMENT_TERMINOLOGY_PUBLICURL=${TERMINOLOGY_PUBLIC_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-terminology-api.yml"
    depends_on:
      - yti-groupmanagement
      - yti-terminology-termed-api
      - yti-postgres
      - yti-elasticsearch
      - yti-activemq
      - yti-keycloak
    links:
      - yti-groupmanagement
      - yti-terminology-termed-api
      - yti-postgres
      - yti-elasticsearch
      - yti-activemq
      - yti-keycloak
    networks:
      - yti-network

  yti-terminology-ui:
    image: "yti-terminology-ui:latest"
    container_name: "yti-terminology-ui"
    privileged: true
    environment:
      - TERMINOLOGY_API_URL
      - MESSAGING_API_URL
      - ANGULAR_PRODUCTION
      - ANGULAR_KEYCLOAK_URL
      - ANGULAR_KEYCLOAK_REALM
      - ANGULAR_KEYCLOAK_CLIENT_ID
      - ANGULAR_BASE_HREF=${TERMINOLOGY_BASE_HREF}
    ports:
      - "9100:80"
    depends_on:
      - yti-terminology-api
      - yti-messaging-api
    links:
      - yti-terminology-api
      - yti-messaging-api
    networks:
      - yti-network

  # DATAMODEL
  yti-datamodel-ui:
    image: "yti-datamodel-ui:latest"
    container_name: "yti-datamodel-ui"
    ports:
      - "9000:80"
    environment:
      - DATAMODEL_API_URL
      - MESSAGING_API_URL
      - ANGULAR_PRODUCTION
      - ANGULAR_KEYCLOAK_URL
      - ANGULAR_KEYCLOAK_REALM
      - ANGULAR_KEYCLOAK_CLIENT_ID
      - ANGULAR_DATAMODEL_DOMAIN
      - ANGULAR_BASE_HREF=${DATAMODEL_BASE_HREF}
    networks:
      - yti-network
    depends_on:
      - yti-datamodel-api
      - yti-messaging-api
    links:
      - yti-datamodel-api
      - yti-messaging-api

  yti-datamodel-api:
    image: "yti-datamodel-api:latest"
    container_name: "yti-datamodel-api"
    ports:
      - "9001:9001"
      - "9004:9004"
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_PUBLIC_URL}
      - ENVIRONMENT_COMMENTS_PUBLICURL=${COMMENTS_PUBLIC_URL}
      - ENVIRONMENT_DATAMODEL_PUBLICURL=${DATAMODEL_PUBLIC_URL}
      - ENVIRONMENT_TERMINOLOGY_PUBLICURL=${TERMINOLOGY_PUBLIC_URL}
      - ENVIRONMENT_GROUPMANAGEMENT_PUBLICURL=${GROUPMANAGEMENT_PUBLIC_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-datamodel-api.yml"
    volumes:
      - ./config:/config:Z
      - /data/logs/yti-datamodel-api:/data/logs/yti-datamodel-api:Z
    depends_on:
      - yti-fuseki
      - yti-groupmanagement
      - yti-elasticsearch
      - yti-terminology-api
      - yti-keycloak
    links:
      - yti-fuseki
      - yti-groupmanagement
      - yti-elasticsearch
      - yti-terminology-api
      - yti-keycloak
    networks:
      - yti-network

  yti-fuseki:
    image: "yti-fuseki:latest"
    container_name: "yti-fuseki"
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - /data/logs/yti-fuseki:/fuseki/logs:Z
      - /data/fuseki:/fuseki/databases
    networks:
      - yti-network

  # COMMENTS
  yti-comments-api:
    image: "yti-comments-api:latest"
    container_name: "yti-comments-api"
    restart: always
    ports:
      - "9701:9701"
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_TERMINOLOGY_PUBLICURL=${TERMINOLOGY_PUBLIC_URL}
      - ENVIRONMENT_DATAMODEL_PUBLICURL=${DATAMODEL_PUBLIC_URL}
      - ENVIRONMENT_GROUPMANAGEMENT_PUBLICURL=${GROUPMANAGEMENT_PUBLIC_URL}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_PUBLIC_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-comments-api.yml"
    volumes:
      - ./config:/config
      - /data/logs/yti-datamodel-api:/data/logs/yti-comments-api:Z
    command: -j -Xmx512M
    depends_on:
      - yti-postgres
      - yti-groupmanagement
      - yti-keycloak
    links:
      - yti-postgres
      - yti-groupmanagement
      - yti-keycloak
    networks:
      - yti-network

  yti-comments-ui:
    image: "yti-comments-ui:latest"
    container_name: "yti-comments-ui"
    ports:
      - "9700:80"
    environment:
      - COMMENTS_API_URL
      - MESSAGING_API_URL
      - ANGULAR_PRODUCTION
      - ANGULAR_KEYCLOAK_URL
      - ANGULAR_KEYCLOAK_REALM
      - ANGULAR_KEYCLOAK_CLIENT_ID
      - ANGULAR_BASE_HREF=${COMMENTS_BASE_HREF}
    volumes:
      - /data/logs/yti-datamodel-api:/data/logs/yti-comments-api:Z
    depends_on:
      - yti-comments-api
      - yti-messaging-api
    links:
      - yti-comments-api
      - yti-messaging-api
    networks:
      - yti-network

  # MESSAGING
  yti-messaging-api:
    image: "yti-messaging-api:latest"
    container_name: "yti-messaging-api"
    restart: always
    ports:
      - "9801:9801"
    environment:
      - ENVIRONMENT_POSTGRES_HOST=${POSTGRES_HOST}
      - ENVIRONMENT_POSTGRES_PORT=${POSTGRES_PORT}
      - ENVIRONMENT_POSTGRES_USERNAME=${POSTGRES_USER}
      - ENVIRONMENT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT_MAIL_HOST=${MAIL_HOST}
      - ENVIRONMENT_MAIL_PORT=${MAIL_PORT}
      - ENVIRONMENT_MAIL_USERNAME=${MAIL_USERNAME}
      - ENVIRONMENT_MAIL_PASSWORD=${MAIL_PASSWORD}
      - ENVIRONMENT_MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - ENVIRONMENT_MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - ENVIRONMENT_MAIL_SMTP_STARTTLS_REQUIRED=${MAIL_SMTP_STARTTLS_REQUIRED}
      - ENVIRONMENT_ADMIN_EMAIL=${ADMIN_EMAIL}
      - ENVIRONMENT_CODELIST_PUBLICURL=${CODELIST_API_URL}
      - ENVIRONMENT_COMMENTS_PUBLICURL=${COMMENTS_API_URL}
      - ENVIRONMENT_TERMINOLOGY_PUBLICURL=${TERMINOLOGY_API_URL}
      - ENVIRONMENT_DATAMODEL_PUBLICURL=${DATAMODEL_API_URL}
      - ENVIRONMENT_GROUPMANAGEMENT_PUBLICURL=${GROUPMANAGEMENT_API_URL}
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-messaging-api.yml"
    volumes:
      - ./config:/config
      - /data/logs/yti-messaging-api:/data/logs/yti-messaging-api:Z
    command: -j -Xmx512M
    depends_on:
      - yti-postgres
      - yti-groupmanagement
      - yti-keycloak
    links:
      - yti-postgres
      - yti-groupmanagement
      - yti-keycloak
    networks:
      - yti-network

  yti-keycloak:
    image: yti-keycloak:latest
    container_name: yti-keycloak
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./config:/config
    environment:
      - KEYCLOAK_USER
      - KEYCLOAK_PASSWORD
      - KEYCLOAK_FRONTEND_URL
      - KEYCLOAK_HTTP_RELATIVE_PATH
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
      - DB_ADDR=${KEYCLOAK_DB_ADDR}
      - DB_PORT=${KEYCLOAK_DB_PORT}
      - DB_DATABASE=${KEYCLOAK_DB_DATABASE}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - yti-postgres
    links:
      - yti-postgres
    networks:
      - yti-network

networks:
  yti-network:
