version: '3'

services:
  # GROUPMANAGEMENT
  
  yti-groupmanagement:
    image: yti-groupmanagement:latest
    volumes:
      - ./config:/config
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-groupmanagement.yml"
      - ANGULAR_CONFIG_URL=http://psi.gora.si/keycloak/auth
      - ANGULAR_CONFIG_REALM=psi
      - ANGULAR_CONFIG_CLIENT_ID=psi-frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yti-groupmanagement.rule=Host(`psi.gora.si`) && PathPrefix(`/groupmanagement-app`) || HeadersRegexp(`Referer`, `/groupmanagement-app/`)"
        - "traefik.http.services.yti-groupmanagement.loadbalancer.server.port=9302"
        - "traefik.http.routers.yti-groupmanagement.entrypoints=web"
        #- "traefik.http.routers.yti-groupmanagement.tls=true"
        #- "traefik.http.routers.yti-groupmanagement.tls.certresolver=leresolver" 
        - "traefik.http.routers.yti-groupmanagement.middlewares=strip-prefix-1,groupmanagement-strip-prefix"   
        - "traefik.http.middlewares.groupmanagement-strip-prefix.stripprefix.prefixes=/groupmanagement-app"
    networks:
      - traefik-public
  
networks:
  traefik-public:
    external: true