version: "3.2"

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik-public
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # make sure the folder is available
      - /mnt/data/portainer:/data
    networks:
      - traefik-public
    deploy:
      labels:
        #### core configs
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`psi.gora.si`) && PathPrefix(`/portainer`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        #### set TLS (https)
        - "traefik.http.routers.portainer.entrypoints=web"
        #- "traefik.http.routers.portainer.tls=true"
        #- "traefik.http.routers.portainer.tls.certresolver=leresolver"
        #### use these middlewares (rules like our-auth,our-retry,our-ratelimit are defined within traefik's labels)
        - "traefik.http.routers.portainer.middlewares=strip-prefix-1,portainer-strip"
        #___ specific middleware rule for this service
        - "traefik.http.middlewares.portainer-strip.stripprefix.prefixes=/portainer"
      
      mode: replicated
      placement:
        constraints: [node.role == manager]          

networks:
  traefik-public:
    external: true
