version: '3'

services:
      
  # ACTIVEMQ

  yti-activemq:
    image: yti-activemq:latest
    ports:
      - "9900:8161"
      - "9901:61616"
    environment:
      - "ARTEMIS_USERNAME=yti"
      - "ARTEMIS_PASSWORD=test"
      - "ARTEMIS_MIN_MEMORY=512M"
      - "ARTEMIS_MAX_MEMORY=512M"
    volumes:
      - /data/logs/yti-activemq:/var/lib/artemis/log:z
    networks:
      - traefik-public    
  
  # CODELIST

  yti-codelist-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.22
    ports:
     - "9610:9200"
    environment:
     - xpack.security.enabled=false
     - cluster.name=yti-codelist-elasticsearch
     - http.host=0.0.0.0
     - transport.host=0.0.0.0
     - network.publish_host=127.0.0.1
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
     - traefik-public

  yti-codelist-ui:
    image: yti-codelist-ui:latest
    environment:
     - ANGULAR_CONFIG_URL=http://psi.gora.si/keycloak/auth
     - ANGULAR_CONFIG_REALM=psi
     - ANGULAR_CONFIG_CLIENT_ID=psi-frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yti-codelist.rule=Host(`psi.gora.si`) && PathPrefix(`/codelist-app`) || HeadersRegexp(`Referer`, `/codelist-app/`)"
        - "traefik.http.services.yti-codelist.loadbalancer.server.port=80"
        - "traefik.http.routers.yti-codelist.entrypoints=web"
        #- "traefik.http.routers.yti-codelist.tls=true"
        #- "traefik.http.routers.yti-codelist.tls.certresolver=leresolver" 
        - "traefik.http.routers.yti-codelist.middlewares=strip-prefix-1,codelist-strip-prefix"   
        - "traefik.http.middlewares.codelist-strip-prefix.stripprefix.prefixes=/codelist-app"
    networks:
     - traefik-public

  yti-codelist-content-intake-service:
    image: yti-codelist-content-intake-service:latest
    ports:
     - "9602:9602"
     - "9603:9603"
     - "19602:19602"
    volumes:
     - ./config:/config
     - /tmp/data/yti/yti-codelist-intake:/data/yti/yti-codelist-intake
    command: -j -Xmx2048M -a --spring.profiles.active=default,docker --spring.config.location=/config/application.yml,/config/yti-codelist-content-intake-service.yml
    networks:
     - traefik-public

  yti-codelist-public-api-service:
    image: yti-codelist-public-api-service:latest
    ports:
     - "9601:9601"
     - "19601:19601"
    volumes:
     - ./config:/config
     - /tmp/data/yti/yti-codelist-api:/data/yti/yti-codelist-api
     - /data/logs/yti-codelist-api:/data/logs/yti-codelist-api:Z
    command: -j -Xmx512M -a --spring.profiles.active=default,docker --spring.config.location=/config/application.yml,/config/yti-codelist-public-api-service.yml
    networks:
     - traefik-public
 
  # TERMINOLOGY

  yti-terminology-termed-api:
    image: "yti-terminology-termed-api:latest"
    environment:
     - SPRING_PROFILES_ACTIVE=default,docker
     - SPRING_CONFIG_LOCATION=/config/yti-terminology-termed-api.properties
    ports:
     - "9102:8080"
    volumes:
     - ./config:/config:Z
     - /data/logs/yti-terminology-termed-api:/data/logs/yti-terminology-termed-api:Z
    networks:
     - traefik-public

  yti-terminology-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.22
    ports:
     - "9104:9200"
    environment:
     - xpack.security.enabled=false
     - transport.host=127.0.0.1
     - http.host=0.0.0.0
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
     - traefik-public

  yti-terminology-api:
    image: "yti-terminology-api:latest"
    environment:
     - SPRING_PROFILES_ACTIVE=default,docker
     - SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-terminology-api.yml
    ports:
     - "9101:9101"
     - "9103:9103"
    volumes:
     - ./config:/config:Z
     - /data/logs/yti-terminology-api:/data/logs/yti-terminology-api:Z
    networks:
     - traefik-public

  yti-terminology-ui:
    image: "yti-terminology-ui:latest"
    environment:
     - ANGULAR_CONFIG_URL=http://psi.gora.si/keycloak/auth
     - ANGULAR_CONFIG_REALM=psi
     - ANGULAR_CONFIG_CLIENT_ID=psi-frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yti-terminology.rule=Host(`psi.gora.si`) && PathPrefix(`/terminology-app`) || HeadersRegexp(`Referer`, `/terminology-app/`)"
        - "traefik.http.services.yti-terminology.loadbalancer.server.port=80"
        - "traefik.http.routers.yti-terminology.entrypoints=web"
        #- "traefik.http.routers.yti-terminology.tls=true"
        #- "traefik.http.routers.yti-terminology.tls.certresolver=leresolver" 
        - "traefik.http.routers.yti-terminology.middlewares=strip-prefix-1,terminology-strip-prefix"   
        - "traefik.http.middlewares.terminology-strip-prefix.stripprefix.prefixes=/terminology-app"
    networks:
     - traefik-public
 
  # DATAMODEL

  yti-datamodel-elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.22"
    ports:
     - "9002:9200"
    environment:
     - xpack.security.enabled=false
     - cluster.name=yti-datamodel-elasticsearch
     - http.host=0.0.0.0
     - network.publish_host=127.0.0.1
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
     - /data/logs/yti-datamodel-elasticsearch:/usr/share/elasticsearch/logs:z
    networks:
     - traefik-public
     
  yti-datamodel-ui:
    image: "yti-datamodel-ui:latest"
    environment:
     - ANGULAR_CONFIG_URL=http://psi.gora.si/keycloak/auth
     - ANGULAR_CONFIG_REALM=psi
     - ANGULAR_CONFIG_CLIENT_ID=psi-frontend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yti-datamodel.rule=Host(`psi.gora.si`) && PathPrefix(`/datamodel-app`) || HeadersRegexp(`Referer`, `/datamodel-app/`)"
        - "traefik.http.services.yti-datamodel.loadbalancer.server.port=80"
        - "traefik.http.routers.yti-datamodel.entrypoints=web"
        #- "traefik.http.routers.yti-datamodel.tls=true"
        #- "traefik.http.routers.yti-datamodel.tls.certresolver=leresolver"         
        - "traefik.http.routers.yti-datamodel.middlewares=strip-prefix-1,datamodel-stripprefix"   
        - "traefik.http.middlewares.datamodel-stripprefix.stripprefix.prefixes=/datamodel-app"
        #- "traefik.http.middlewares.root-redirect.redirectregex.regex=^(https?:\\/\\/[^\\/]+)\\/?$$"
        #- "traefik.http.middlewares.root-redirect.redirectregex.replacement=$${1}/datamodel-app/"
    networks:
     - traefik-public

  yti-datamodel-api:
    image: "yti-datamodel-api:latest"
    ports:
     - "9001:9001"
     - "9004:9004"
    environment:
     - SPRING_PROFILES_ACTIVE=docker
     - SPRING_CONFIG_LOCATION=/config/application.yml,/config/yti-datamodel-api.yml
    volumes:
     - ./config:/config:Z
     - /data/logs/yti-datamodel-api:/data/logs/yti-datamodel-api:Z
    networks:
     - traefik-public

  yti-fuseki:
    image: "yti-fuseki:latest"
    ports:
     - "3030:3030"
    volumes:
     - /data/logs/yti-fuseki:/fuseki/logs:Z
     - /data/fuseki:/fuseki/databases
    networks:
     - traefik-public


  # COMMENTS 
  
  yti-comments-api:
    image: "yti-comments-api:latest"
    ports:
      - "9701:9701"
    volumes:
      - ./config:/config
      - /data/logs/yti-datamodel-api:/data/logs/yti-comments-api:Z
    command: -j -Xmx2048M -a --spring.profiles.active=default,docker --spring.config.location=/config/application.yml,/config/yti-comments-api.yml
    networks:
      - traefik-public
     
  yti-comments-ui:
    image: "yti-comments-ui:latest"
    environment:
      - ANGULAR_CONFIG_URL=http://psi.gora.si/keycloak/auth
      - ANGULAR_CONFIG_REALM=psi
      - ANGULAR_CONFIG_CLIENT_ID=psi-frontend
    volumes:
      - /data/logs/yti-datamodel-api:/data/logs/yti-comments-api:Z
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yti-comments-ui.rule=Host(`psi.gora.si`) && PathPrefix(`/comments-app`) || HeadersRegexp(`Referer`, `/comments-app/`)"
        - "traefik.http.services.yti-comments-ui.loadbalancer.server.port=80"
        - "traefik.http.routers.yti-comments-ui.entrypoints=web"
        #- "traefik.http.routers.yti-comments-ui.tls=true"
        #- "traefik.http.routers.yti-comments-ui.tls.certresolver=leresolver"     
        - "traefik.http.routers.yti-comments-ui.middlewares=strip-prefix-1,comments-strip-prefix"     
        - "traefik.http.middlewares.comments-strip-prefix.stripprefix.prefixes=/comments-app"
    networks:
      - traefik-public

  # MESSAGING     

  yti-messaging-api:
    image: "yti-messaging-api:latest"
    ports:
      - "9801:9801"
    volumes:
      - ./config:/config
      - /data/logs/yti-messaging-api:/data/logs/yti-messaging-api:Z
    command: -j -Xmx2048M -a --spring.profiles.active=default,docker --spring.config.location=/config/application.yml,/config/yti-messaging-api.yml
    networks:
      - traefik-public
     
  # KEYCLOAK
  yti-keycloak:
    image: jboss/keycloak
    volumes:
      - ./config:/config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=yti-postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - "DB_PASSWORD=#{PASSWORD}"
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=http://psi.gora.si/keycloak/auth/
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.yti-keycloak.rule=Host(`psi.gora.si`) && PathPrefix(`/keycloak`) || HeadersRegexp(`Referer`, `/keycloak/`) || PathPrefix(`/auth`)"
        - "traefik.http.services.yti-keycloak.loadbalancer.server.port=8080"
        - "traefik.http.routers.yti-keycloak.entrypoints=web"
        #- "traefik.http.routers.yti-keycloak.tls=true"
        #- "traefik.http.routers.yti-keycloak.tls.certresolver=leresolver"
        - "traefik.http.routers.yti-keycloak.middlewares=strip-prefix-1,keycloak-strip-prefix"      
        - traefik.http.middlewares.keycloak-strip-prefix.stripprefix.prefixes=/keycloak          
    networks:
      - traefik-public    

networks:
  traefik-public:
    external: true