version: "3.3"

services:
  traefik:
    image: "traefik:v2.5"
    command:
      - --log.level=INFO
      - --entrypoints.web.address=:80
     # - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode=true
      - --providers.docker.network=traefik-public
      - --api
      - --api.dashboard=true
     # - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      # update your email here
     # - --certificatesresolvers.leresolver.acme.email=ales.bernik@gora.si
      # Make sure the this file is available and permission is set correctly
      - --certificatesresolvers.leresolver.acme.storage=/le/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
     # - "443:443"
    networks:
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Make sure the volume folder is created
      - "/mnt/data/traefik/acme.json:/le/acme.json"
    deploy:
      labels:
        # Dashboard
        - "traefik.enable=true"
        # Change the host url here
        - "traefik.http.routers.traefik.rule=Host(`psi.gora.si`) && PathPrefix(`/traefik`) || HeadersRegexp(`Referer`, `/traefik/`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        #- "traefik.http.routers.traefik.tls.certresolver=leresolver"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "traefik.http.routers.traefik.middlewares=authtraefik,traefik-strip-prefix"
        - traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes=/traefik
        # Change the auth password here
        - "traefik.http.middlewares.authtraefik.basicauth.users=admin:$$2y$$05$$V7ejSm.7VaZGtrzH5Ywnze7Nbfh8YspK5CkrLen3HZUscZVvtuLR6" # user/password (admin:varnogeslo)

        # global redirect to https
       # - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
       # - "traefik.http.routers.http-catchall.entrypoints=web"
       # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

        # middleware redirect
       # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
       # middleware
        - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_-]+)$$"
        - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/"
        - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"

networks:
  traefik-public:
    external: true
