---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false

management:
  # Set management port to 10000 + server.port (i.e. e.g. if server.port = 9601, management port = 19601).
  port: 1${server.port}

thread:
  pool:
    idle-timeout: 10000
    max: 50
    min: 10

environment:
  languages: sl,en
  defaultLanguage: sl
  codelist-elastic:
    host: 127.0.0.1
    port: 9610
  datamodel-elastic:
    host: 127.0.0.1
    port: 9002
  terminology-elastic:
    host: 127.0.0.1
    port: 9104
  activemq:
    host: 127.0.0.1
    port: 9901
  fuseki:
    host: 127.0.0.1
    port: 3030
  termed-api:
    host: 127.0.0.1
    port: 9102
  postgres:
    host: 127.0.0.1
    port: 5432
    username: postgres
    password: Jaz!Ti!On
  codelist:
    public-host: localhost:9600
    #public-host: koodistot.dev.yti.cloud.vrk.fi
    public-url: http://${environment.codelist.public-host}
    api-url: http://localhost:9601
    #api-url: ${environment.codelist.public-url}
  terminology:
    public-url: http://localhost:9100
    url: http://localhost:9103
    #url: ${environment.terminology.public-url}
  datamodel:
    public-url: http://localhost:9000
    url: http://localhost:9004
    #url: ${environment.datamodel.public-url}
  groupmanagement:
    public-url: http://localhost:9302
    url: http://localhost:9302
    #url: https://rhp.dev.yti.cloud.vrk.fi
  comments:
    #public-host: kommentit.dev.yti.cloud.vrk.fi
    public-host: localhost:9700
    public-url: http://${environment.comments.public-host}
  messaging:
    url: http://localhost:9801
    enabled: true
    
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: psi
  resource: psi-backend
  bearer-only: true
  ssl-required: external
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      enabled: false
  jpa:
    #show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none

management:
  # Set management port to 10000 + server.port (i.e. e.g. if server.port = 9601, management port = 19601).
  port: 1${server.port}

thread:
  pool:
    idle-timeout: 10000
    max: 50
    min: 10

environment:
  languages: sl,en
  defaultLanguage: sl
  codelist-elastic:
    host: yti-codelist-elasticsearch
    port: 9200
    cluster: yti-codelist-elasticsearch
  datamodel-elastic:
    host: yti-datamodel-elasticsearch
    port: 9200
  terminology-elastic:
    host: yti-terminology-elasticsearch
    port: 9200
  activemq:
    host: yti-activemq
    port: 61616
  fuseki:
    host: yti-fuseki
    port: 3030
  termed-api:
    host: yti-terminology-termed-api
    port: 8080
  postgres:
    host: yti-postgres
    port: 5432
    username: postgres
    password: password
  codelist:
    public-host: localhost:9600
    public-url: http://${environment.codelist.public-host}
    api-url: http://yti-codelist-public-api-service:9601
  terminology:
    public-url: http://localhost:9100
    url: http://yti-terminology-api:9103
  datamodel:
    public-url: http://localhost:9000
    url: http://yti-datamodel-api:9004
  groupmanagement:
    public-url: http://localhost:9302
    url: http://yti-groupmanagement:9302
  comments:
    public-host: localhost:9700 
    public-url: http://${environment.comments.public-host}
  messaging:
    url: http://localhost:9801
    enabled: true
 
keycloak:
  auth-server-url: http://yti-keycloak:8080/auth
  realm: psi
  resource: psi-backend
  public-client: true
  bearer-only: true
  ssl-required: external
  confidential-port: 0
