---
spring:
  profiles: local

tomcat:
  ajp:
    port: 8009

elasticHost: localhost
elasticPort: 9003
elasticCluster: yti-datamodel-elasticsearch

#endpoint: http://yti-fuseki:3030
endpoint: http://localhost:3030

devMode: true
defaultTermedAPI: http://localhost:9102/api/

defaultGroupManagementAPI: https://rhp-dev.suomi.fi/public-api/
publicGroupManagementAPI: https://rhp-dev.suomi.fi
defaultSuomiCodeServerAPI: https://koodistot-dev.suomi.fi/codelist-api/api/v1/
defaultTermedAPIUser: admin
defaultTermedAPIUserSecret: admin
publicGroupManagementFrontend: https://rhp-dev.suomi.fi
publicSuomiCodeServerFrontend: https://koodistot-dev.suomi.fi
#defaultTerminologyAPI: http://yti-terminology-api:8001/
defaultTerminologyAPI: http://localhost:9103/
publicTerminologyFrontend: https://sanastot-dev.suomi.fi
publicCommentsFrontend: https://kommentit-dev.suomi.fi

publicTermedAPI: http://localhost:9102/

groupmanagement:
  url: https://rhp-dev.suomi.fi
  public.url: https://rhp-dev.suomi.fi

env: local

fake:
  login:
    allowed: true
    mail: "john.doe@example.com"
    firstName: "John"
    lastName: "Doe"

impersonate:
  allowed: true

---
spring:
  profiles: docker

tomcat:
  ajp:
    port: 8009

elasticHost: yti-datamodel-elasticsearch
elasticPort: 9300
elasticCluster: yti-datamodel-elasticsearch

endpoint: http://yti-fuseki:3030

devMode: true
defaultTermedAPI: http://yti-terminology-termed-api:8080/api/

defaultGroupManagementAPI: http://yti-groupmanagement:8002/public-api/
publicGroupManagementAPI: https://rhp-dev.suomi.fi
defaultSuomiCodeServerAPI: https://koodistot-dev.suomi.fi/codelist-api/api/v1/
defaultTermedAPIUser: admin
defaultTermedAPIUserSecret: admin
publicGroupManagementFrontend: https://rhp-dev.suomi.fi
publicSuomiCodeServerFrontend: https://koodistot-dev.suomi.fi
defaultTerminologyAPI: http://yti-terminology-api:8001/
publicTerminologyFrontend: https://sanastot-dev.suomi.fi
publicCommentsFrontend: https://kommentit-dev.suomi.fi

publicTermedAPI: http://yti-terminology-termed-api/

groupmanagement:
  url: http://yti-groupmanagement:8002
  public.url: https://rhp-dev.suomi.fi

env: local

fake:
  login:
    allowed: true
    mail: "john.doe@example.com"
    firstName: "John"
    lastName: "Doe"

impersonate:
  allowed: true

