---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: yti-codelist-public-api-service

server:
  port: 9601

tomcat:
  ajp:
    port: 9604

application:
  publicUrl: ${environment.codelist.public-url}
  contextPath: "/codelist-api"
  access-log: true

groupmanagement:
  url: ${environment.groupmanagement.url}
  publicUrl: ${environment.groupmanagement.public-url}

session:
  timeout-mins: 10

impersonate:
  allowed: true

fake:
  login:
    allowed: true

elasticsearch:
  scheme: ${environment.elasticsearch.scheme}
  host: ${environment.elasticsearch.host}
  port: ${environment.elasticsearch.port}

uri:
  scheme: http
  host: iow.gora.si

---
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: yti-codelist-public-api-service

server:
  port: 9601

application:
  publicUrl: ${environment.codelist.public-url}
  contextPath: "/codelist-api"
  access-log: true

groupmanagement:
  url: ${environment.groupmanagement.url}
  publicUrl: ${environment.groupmanagement.public-url}

session:
  timeout-mins: 10

impersonate:
  allowed: false

fake:
  login:
    allowed: false

elasticsearch:
  scheme: ${environment.elasticsearch.scheme}
  host: ${environment.elasticsearch.host}
  port: ${environment.elasticsearch.port}

uri:
  scheme: http
  host: iow.gora.si
