---
spring:
  profiles: local
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  activemq:
    broker-url: "tcp://localhost:61616"
    user: yti
    password: "test"

tomcat:
  ajp:
    port: 9090

server:
  port: 8001

search:
  host:
    url: yti-terminology-elasticsearch
    port: 9200
    scheme: http

api:
  url: http://yti-terminology-termed-api:8080/api
  user: admin
  pw: admin

groupmanagement:
  url: "https://rhp.dev.yti.cloud.vrk.fi"
  public:
    url: "https://rhp.dev.yti.cloud.vrk.fi"

services:
  codeListUrl: https://koodistot.dev.yti.cloud.vrk.fi
  dataModelUrl: https://tietomallit.dev.yti.cloud.vrk.fi
  groupManagementUrl: https://rhp.dev.yti.cloud.vrk.fi
  commentsUrl: https://kommentit.dev.yti.cloud.vrk.fi
  env: local

fake:
  login:
    allowed: true
    mail: "john.doe@example.com"
    firstName: "John"
    lastName: "Doe"

impersonate:
  allowed: true

migration:
  enabled: true

notify:
  hook:
    url: http://yti-terminology-api:8001/notify

application:
  public:
    url: https://sanastot.dev.yticloud.vrk.fi

---
spring:
  profiles: docker
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  activemq:
    broker-url: "tcp://yti-activemq:61616"
    user: yti
    password: "test"

tomcat:
  ajp:
    port: 9090

server:
  port: 8001

search:
  host:
    url: yti-terminology-elasticsearch
    port: 9200
    scheme: http

api:
  url: http://yti-terminology-termed-api:8080/api
  user: admin
  pw: admin

groupmanagement:
  url: "http://yti-groupmanagement:8002"
  public:
    url: "http://localhost:9602"

services:
  codeListUrl: https://koodistot.dev.yticloud.vrk.fi
  dataModelUrl: https://tietomallit.dev.yticloud.vrk.fi
  groupManagementUrl: https://rhp.dev.yticloud.vrk.fi
  commentsUrl: https://kommentit.dev.yticloud.vrk.fi
  env: docker

fake:
  login:
    allowed: true
    mail: "john.doe@example.com"
    firstName: "John"
    lastName: "Doe"

impersonate:
  allowed: true

migration:
  enabled: true

notify:
  hook:
    url: http://yti-terminology-api:8001/notify

application:
  public:
    url: https://sanastot.dev.yticloud.vrk.fi
