---
spring:
  profile: local
  application:
    name: yti-groupmanagement
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${environment.postgres.host}:${environment.postgres.port}/${service.database-name}
    username: ${environment.postgres.username}
    password: ${environment.postgres.password}
  flyway:
    table: schema_version

service:
  database-name: yti_groupmanagement

defaultLanguage: ${environment.defaultLanguage}

server:
  port: 9302

tomcat:
  ajp:
    port: 9300

registration:
  url: https://id.eduuni.fi/signup?returnUrl=https://yhteentoimiva.suomi.fi

groupmanagement:
  url: ${environment.groupmanagement.url}

environment:
  url: ${environment.groupmanagement.public-url}

send:
  admin:
    emails: false
    
admin:
  email: "admin@localhost"

application:
  codeListUrl: ${environment.codelist.public-url}
  dataModelUrl: ${environment.datamodel.public-url}
  terminologyUrl: ${environment.terminology.public-url}
  commentsUrl: ${environment.comments.public-url}
  env: local
  messagingEnabled: ${environment.messaging.enabled}

jwt:
  secret: TESTSECRET

fake:
  login:
    allowed: true

impersonate:
  allowed: true

---
spring:
  profile: docker
  application:
    name: yti-groupmanagement
  mail:
    host: ${environment.mail.host}
    port: ${environment.mail.port}
    username: ${environment.mail.username}
    password: ${environment.mail.password}
    properties:
      mail:
        smtp:
          auth: ${environment.mail.smtp.auth}
          starttls:
            enable: ${environment.mail.smtp.starttls.enable}
            required: ${environment.mail.smtp.starttls.required}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${environment.postgres.host}:${environment.postgres.port}/${service.database-name}
    username: ${environment.postgres.username}
    password: ${environment.postgres.password}
  flyway:
    table: schema_version

service:
  database-name: yti_groupmanagement

defaultLanguage: ${environment.defaultLanguage}

server:
  port: 9302

tomcat:
  ajp:
    port: 9300

registration:
  url: https://id.eduuni.fi/signup?returnUrl=https://yhteentoimiva.suomi.fi

groupmanagement:
  url: ${environment.groupmanagement.url}

environment:
  url: ${environment.groupmanagement.public-url}

send:
  admin:
    emails: false

admin:
  email: ${environment.admin.email}

application:
  codeListUrl: ${environment.codelist.public-url}
  dataModelUrl: ${environment.datamodel.public-url}
  terminologyUrl: ${environment.terminology.public-url}
  commentsUrl: ${environment.comments.public-url}
  env: prod
  messagingEnabled: ${environment.messaging.enabled}

jwt:
  secret: TESTSECRET

fake:
  login:
    allowed: false

impersonate:
  allowed: false
